name: Tests

on:
  push:
    branches:
    - master
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        version: [0.1.2]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup recontent
      uses: ./
      with:
        version: ${{ matrix.version }}

    - name: Capture recontent version installed
      # Required to use CLI
      env:
        RECONTENT_API_KEY: dummy-api-key
      # See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      run: |
        export RECONTENT_VERSION=$( recontent --version )
        echo 'RECONTENT_VERSION_INSTALLED<<EOF' >> $GITHUB_ENV
        recontent --version >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Verify
      shell: python
      env:
        RECONTENT_VERSION_EXPECTED: ${{ matrix.version }}
      run: |
        import sys, os
        sys.exit(
            int(not os.environ["RECONTENT_VERSION_EXPECTED"] in os.environ["RECONTENT_VERSION_INSTALLED"])
        )
